[package]
name = "server-launcher"
version = "0.1.0"
authors = ["Tom_The_Geek <23531706+Geek202@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webhook = "1.0.1"
tokio = "0.2"
